name: "Compliance"

on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  
permissions:
  pull-requests: write #what is this permission for?

jobs:
  compliance:
    uses: open-sauced/open-sauced/.github/workflows/compliance.yml@main