name: Log organization statistics
on:
  schedule:
    # https://crontab.guru/every-day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  logOctokitStats:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: MyComOrg1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cat << EOF
          result: ${{ steps.stats.outputs.data }}
          EOF
