name: Ping
env:
  owner: mero
  repo: example-event-dispatcher-workflow
on:
  repository_dispatch:
    types: [run-ping, webhook]
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello from ping.yaml"
          echo "ref = ${{ github.event.client_payload.integration }}"
