name: "test env not propagated to called workflow"

on:
  push:
env:
  WHOAMI: caller

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env 
        run: |
          echo "value of env.WHOAMI: ${{ env.WHOAMI }}"
          echo "value of WHOAMI: $WHOAMI"
          echo "value of GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "value of HOME: ${HOME}"
          echo "value of GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "value of GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "value of GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "value of GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "value of GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "value of GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "value of GITHUB_ENV: ${GITHUB_ENV}"
          echo "value of GITHUB_JOB: ${GITHUB_JOB}"
          echo "value of GITHUB_PATH: ${GITHUB_PATH}"
          echo "value of GITHUB_REF: ${GITHUB_REF}"
          echo "value of GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "value of GITHUB_REF_PROTECTED: ${GITHUB_REF_PROTECTED}"
          echo "value of GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
          echo "value of GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          echo "value of GITHUB_RETENTION_DAYS: ${GITHUB_RETENTION_DAYS}"
          echo "value of GITHUB_RUN_ATTEMPT: ${GITHUB_RUN_ATTEMPT}"
          echo "value of GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "value of GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "value of GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          echo "value of GITHUB_SHA: ${GITHUB_SHA}"
          echo "value of GITHUB_STEP_SUMMARY: ${GITHUB_STEP_SUMMARY}"
          echo "value of GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "value of GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "value of RUNNER_ARCH: ${RUNNER_ARCH}"
          echo "value of RUNNER_NAME: ${RUNNER_NAME}"
          echo "value of RUNNER_OS: ${RUNNER_OS}"
          echo "value of RUNNER_TEMP: ${RUNNER_TEMP}"
          echo "value of RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}"
  call-printenv-workflow:
    uses: ./.github/workflows/print-env.yml
