name: "test env not propagated to called workflow"

on:
  push:
env:
  WHOAMI: caller

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env 
        run: |
          echo "value of env.WHOAMI: ${{ env.WHOAMI }}"
          echo "value of WHOAMI: $WHOAMI"
          echo "value of GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "value of HOME: ${HOME}"
  call-printenv-workflow:
    uses: ./.github/workflows/print-env.yml
