name: "test env not propagated to called workflow"

on:
  push:
env:
  WHOAMI: caller

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env 
        run: |
          echo "value of env.WHOAMI: ${{ env.WHOAMI }}"
          echo "value of WHOAMI: $WHOAMI"
  call-printenv-workflow:
    uses: ./.github/workflows/print-env.yml
