name: "Sample workflow reuse"

on:
  push:

jobs:
  call-sample-workflow-1:
    uses: MyComOrg1/standard-workflows/.github/workflows/sample-workflow-1.yml@main
    with:
      majorVersion: "8"
  call-local-workflow:
    needs: call-sample-workflow-1
    uses: ./.github/workflows/local-workflow.yml
    with:
      majorVersion: "11"
      optionalMinorVersion: "0"
